# 1-Create random tensor with shape (7, 7)

In [ ]:
import torch
tensor_A = torch.rand(7, 7)
print(tensor_A)

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])


# 2-Perform matrix multiplication

In [12]:
# Create another random tensor with shape (1, 7)
tensor_B = torch.rand(1, 7)

# Transpose tensor_B to make it (7, 1)
tensor_B_T = tensor_B.T

# Perform matrix multiplication
result = torch.matmul(tensor_A, tensor_B_T)
print(result)
print(result.shape)  # (7, 1)


tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])
torch.Size([7, 1])


In [13]:
import torch

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Transpose tensor_B to (7, 1)
tensor_B_T = tensor_B.T

# Matrix multiply tensors
result = torch.matmul(tensor_A, tensor_B_T)
print(result)
print(result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


# 3-Create two random tensors of shape (2, 3) and send them to GPU

In [15]:
import torch

# Set random seed for reproducibility
torch.manual_seed(1234)

# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors of shape (2, 3) and send them to GPU
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

print(tensor_A)
print(tensor_B)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


# 4- Perform matrix multiplication

In [16]:
# Perform matrix multiplication
result = torch.matmul(tensor_A, tensor_B.T)

print(result)
print(result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
torch.Size([2, 2])


# 5-Find max and min values in the tensors

In [17]:
# Find max and min values in the tensors
max_val = tensor_A.max()
min_val = tensor_B.min()

print("Max value:", max_val)
print("Min value:", min_val)


Max value: tensor(0.7006)
Min value: tensor(0.0518)


# 6-Find index of max & min

In [18]:
# Find index of max
max_idx = tensor_A.argmax()

# Find index of min
min_idx = tensor_B.argmin()

print("Index of max value:", max_idx)
print("Index of min value:", min_idx)


Index of max value: tensor(5)
Index of min value: tensor(0)


#  7-Remove single dimensions

In [19]:
import torch

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand((1, 1, 1, 10))

print(tensor, tensor.shape)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

print(tensor_squeezed, tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
